[package]
name = "antbox"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
log.workspace = true
logging-options.workspace = true
speedy2d.workspace = true
