[workspace]
resolver = "3"
members = [
  "antbox",
  "logging-options",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
clap = "4.5.53"
env_logger = "0.11.8"
log = "0.4.28"
speedy2d = "2.1.0"
